
[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [ ".cache", "dist/_pagefind" ]


[[headers]]
    for = "/*"
    [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "autoplay=(), camera=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), publickey-credentials-get=()"
    for = "/pagefind/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
